# frozen_string_literal: true

require 'hive/worker'

module Hive
  class Worker
    # The Shell worker
    class Shell < Worker
      def initialize(options = {})
        @default_component ||= "#{self.class} [#{$PROCESS_ID}]"
        super
      end

      def pre_script(job, file_system, script); end

      # List of autogenerated queues for the worker
      def autogenerated_queues
        @log.info('Autogenerating queues')
        [
          @queue_prefix,
          "#{@queue_prefix} #{@device_location}",
          "#{@queue_prefix} #{@device_building_location}",
          "#{@queue_prefix} bash"
        ].map! { |element| element.to_s.downcase.strip.tr(' ', '_').delete('"') }.reject(&:empty?).uniq
      end

      # Parameters for uniquely identifying the device
      def hive_mind_device_identifiers
        { id: @hive_id }
      end
    end
  end
end
